# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type_graph', models.CharField(max_length=10)),
                ('x', models.CharField(max_length=10)),
                ('y', models.CharField(max_length=10)),
            ],
        ),
    ]
