# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160324_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Upload_CSV_File',
            field=models.FileField(default=2, upload_to='documents/%Y/%m/%d'),
        ),
    ]
