# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160324_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Upload_CSV_File',
        ),
    ]
