# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_user_file_csv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='file_csv',
            field=models.FileField(default='/no-file.csv', upload_to='files/'),
        ),
    ]
